#!/bin/bash
set -e

mysql --local-infile=1 -uroot -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" <<-EOSQL
SET GLOBAL local_infile = 1;

CREATE TABLE IF NOT EXISTS cc_general (
  CUST_ID TEXT,
  BALANCE DOUBLE,
  BALANCE_FREQUENCY DOUBLE,
  PURCHASES DOUBLE,
  ONEOFF_PURCHASES DOUBLE,
  INSTALLMENTS_PURCHASES DOUBLE,
  CASH_ADVANCE DOUBLE,
  PURCHASES_FREQUENCY DOUBLE,
  ONEOFF_PURCHASES_FREQUENCY DOUBLE,
  PURCHASES_INSTALLMENTS_FREQUENCY DOUBLE,
  CASH_ADVANCE_FREQUENCY DOUBLE,
  CASH_ADVANCE_TRX BIGINT,
  PURCHASES_TRX BIGINT,
  CREDIT_LIMIT DOUBLE,
  PAYMENTS DOUBLE,
  MINIMUM_PAYMENTS DOUBLE,
  PRC_FULL_PAYMENT DOUBLE,
  TENURE BIGINT
);

LOAD DATA LOCAL INFILE '/docker-entrypoint-initdb.d/dataset.csv'
INTO TABLE cc_general
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
EOSQL

echo "==> cc_general loaded from dataset.csv"
